### PR TITLE
Merged commit to support other query types, starting with 'Or'

### PR DESCRIPTION
**Pull request by mbhnyc**
When using retrieve_multiple.

### CODE REVIEW

**Comment by mbhnyc** [comment]
Ok, new PR squashed and addressed comments, should be good?

**Comment by mbhnyc** [comment]
ahh looks like tests are failing now, looking into it.

**Comment by mbhnyc** [comment]
should pass now - needed `||=` so a passed nil from above doesn't override the param default

**Comment by jheth** [comment]
Great! Thanks @mbhnyc . I appreciate you working through this.

**Pull request merged**
