### PR TITLE
On-Premise Authentication Support

### PR DESCRIPTION
**Pull request by jheth**
Supports multiple regions and On-Premise Authentication.  Manually merged in kam's changes, did a little refactoring and added specs for coverage.

### CODE REVIEW

**Comment by sribalakumar** [comment]
@kam I am trying to use the gem to fetch contact details for an on-premise version within a local network and also via IFD. And I am in need of some clarifications on the authentication part. 

This is the example for on-demand :
client = DynamicsCRM::Client.new({organization_name: "orgname"})
client.authenticate('user@orgname.onmicrosoft.com', 'password')

If you can give example snippets for on-premise & IFD like the above it should help me.

**Comment by kam** [comment]
@sribalakumar you'll need to do something like this:

```ruby
client = DynamicsCRM::Client.new({organization_name: "orgname" hostname: "host.example.com"})
client.authenticate(username, password)
contact = client.retrieve('lead', lead_id)
```

With username, it should be the same as what you would use when you login to the web interface. So if you login as 'domainname\username' you will have to use that in full.

**Comment by sribalakumar** [comment]
@kam 
with client as 
```
    client = DynamicsCRM::Client.new({organization_name: "orgname", hostname: "host.example.com"})
```
Clarifying for the function call 
```
    build_on_premise_request(username, password, region, login_url) 
```
 will this have region = "https://host.example.com/XRMServices/2011/Organization.svc" ? 
For on-demand calls, variable region looks something like this "urn:crmna:dynamics.com". Is this the right behavior for on-premise or am I missing something ?

**Comment by sribalakumar** [comment]
@kam 
```
client = DynamicsCRM::Client.new({organization_name: "fdcrm", hostname: "internal.int.com:5556"})
```
gives an object of the form
```
<DynamicsCRM::Client:0x007f871be0ad90 @organization_name="fdcrm", @hostname="internal.int.com:5556", @organization_endpoint="https://internal.int.com:5556/XRMServices/2011/Organization.svc", @caller_id=nil, @login_url="https://login.microsoftonline.com/RST2.srf", @region="urn:crmna:dynamics.com">
```
guess the login_url and the region is wrong here, when I open https://internal.int.com:5556/fdcrm/XRMServices/2011/Organization.svc?wsdl=wsdl0 and tried to look up for 
// Login URL: Policy -> Issuer -> Address (as described in client.rb in the gem)
// Region: SecureTokenService -> AppliesTo (as described in client.rb in the gem)
XML snippet for login url goes like
```
<wsp:Policy>
<sp:IssuedToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
<Issuer xmlns="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
<Address xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</Address>
<Metadata xmlns="http://www.w3.org/2005/08/addressing">
<Metadata xmlns="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<wsx:MetadataSection xmlns="">
<wsx:MetadataReference>
<Address xmlns="http://www.w3.org/2005/08/addressing">https://adfs.int.com/adfs/services/trust/mex</Address>
</wsx:MetadataReference>
</wsx:MetadataSection>
</Metadata>
</Metadata>
</Issuer>
<sp:RequestSecurityTokenTemplate>
<trust:KeyType xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512">
http://docs.oasis-open.org/ws-sx/ws-trust/200512/SymmetricKey
</trust:KeyType>
<trust:KeySize xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512">256</trust:KeySize>
<trust:Claims xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512" Dialect="http://schemas.xmlsoap.org/ws/2005/05/identity">
<wsid:ClaimType xmlns:wsid="http://schemas.xmlsoap.org/ws/2005/05/identity" Uri="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"/>
</trust:Claims>
<trust:KeyWrapAlgorithm xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p</trust:KeyWrapAlgorithm>
<trust:EncryptWith xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://www.w3.org/2001/04/xmlenc#aes256-cbc</trust:EncryptWith>
<trust:SignWith xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://www.w3.org/2000/09/xmldsig#hmac-sha1</trust:SignWith>
<trust:CanonicalizationAlgorithm xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://www.w3.org/2001/10/xml-exc-c14n#</trust:CanonicalizationAlgorithm>
<trust:EncryptionAlgorithm xmlns:trust="http://docs.oasis-open.org/ws-sx/ws-trust/200512">http://www.w3.org/2001/04/xmlenc#aes256-cbc</trust:EncryptionAlgorithm>
</sp:RequestSecurityTokenTemplate>
<wsp:Policy>
<sp:RequireInternalReference/>
</wsp:Policy>
</sp:IssuedToken>
</wsp:Policy>
```
and the snippet for SecureTokenService 
```
<ms-xrm:SecureTokenService>
<ms-xrm:Identifier>http://adfs.int.com/adfs/services/trust</ms-xrm:Identifier>
</ms-xrm:SecureTokenService>
```
can you help me with constructing a proper client object please.

**Comment by przemad** [comment]
Hi! Any progress on this?

**Comment by mkweick** [comment]
Any luck constructing a proper client object for On-Premise with IFD? I'm struggling with same issue.

**Pull request merged**
